name: CI workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHELLCHECK_OPTS: -e SC2016,SC1090
          SHFMT_OPTS: -s -w
        with:
          sh_checker_comment: true
      - name: Commit any formatting updates
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting updates
          branch: ${{ github.head_ref }}